-- Made by LukakoZabijak (lukakozabijak) on discord, killerox3905 on Roblox.

local config = {}

config.DeveloperProductId = 3571254188
config.PurchaseButtonText = "Claim All For R$99"
config.Rewards = {
	{ Name = "50 Cash", Image = "rbxassetid://111803780541868", Type = "Coins", Amount = 50 },
	{ Name = "100 Cash", Image = "rbxassetid://111803780541868", Type = "Coins", Amount = 100 },
	{ Name = "5 Diamonds", Image = "rbxassetid://14733370594", Type = "Diamonds", Amount = 5 },
	{ Name = "200 Cash", Image = "rbxassetid://111803780541868", Type = "Coins", Amount = 200 },
	{ Name = "10 Diamonds", Image = "rbxassetid://14733370594", Type = "Diamonds", Amount = 10 },
	{ Name = "500 Cash", Image = "rbxassetid://111803780541868", Type = "Coins", Amount = 500 },
	{ Name = "50 Diamonds", Image = "rbxassetid://14733370594", Type = "Diamonds", Amount = 50 },
}

config.developer_product_id = config.DeveloperProductId
config.purchase_button_text = config.PurchaseButtonText
config.rewards = config.Rewards

return config
